name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - node-version: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run ci
        env:
          # Please get your own free key if you want to test yourself
          BROWSERSTACK_USERNAME: sitepenlabs1
          BROWSERSTACK_ACCESS_KEY: xm1uYrJuV3gZMJqCyZJX
          SAUCE_USERNAME: dojo2-ts-ci
          SAUCE_ACCESS_KEY: e92610e3-834e-4bec-a3b5-6f7b9d874601
      - if: ${{ matrix.node-version == 16 }}
        uses: codecov/codecov-action@v2
